// This file will be auto-generated by the Supabase CLI
// to create TypeScript types from your database schema.
// For now, we will define it manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          created_at?: string
        }
      }
      user_profiles: {
        Row: {
          id: string // This is the Firebase UID
          organization_id: string
          role: "Admin" | "Member"
          created_at: string
          email: string
        }
        Insert: {
          id: string
          organization_id: string
          role: "Admin" | "Member"
          created_at?: string
          email: string
        }
        Update: {
          id?: string
          organization_id?: string
          role?: "Admin" | "Member"
          created_at?: string
          email?: string
        }
      }
      proposals: {
        Row: {
          id: number
          organization_id: string
          created_by: string
          title: string
          background: string
          status: "Draft" | "In-Review" | "Decided"
          created_at: string
        }
        Insert: {
          id?: number
          organization_id: string
          created_by: string
          title: string
          background: string
          status?: "Draft" | "In-Review" | "Decided"
          created_at?: string
        }
        Update: {
          id?: number
          organization_id?: string
          created_by?: string
          title?: string
          background?: string
          status?: "Draft" | "In-Review" | "Decided"
          created_at?: string
        }
      }
    }
    Views: {}
    Functions: {}
  }
}
