import jsPDF from 'jspdf';
import type { LedgerEntry } from '../hooks/useStrategicLedger';

// Define strict palette from spec
const COLORS = {
    bg: '#FFFFFF',
    primaryText: '#374151', // Charcoal
    navy: '#0F172A',        // Headers/Accents
    border: '#E5E7EB',      // Light Grey
    rationaleBorder: '#9CA3AF',
    warning: '#991B1B',     // Deep Red
    badgeFormalBg: '#EFF6FF',
    badgeFormalText: '#1D4ED8',
    badgeOutBg: '#FEF2F2',
    badgeOutText: '#991B1B'
};

const hexToRgb = (hex: string): [number, number, number] => {
    const r = parseInt(hex.slice(1, 3), 16);
    const g = parseInt(hex.slice(3, 5), 16);
    const b = parseInt(hex.slice(5, 7), 16);
    return [r, g, b];
};

export const exportStrategicLedgerToPDF = async (
    entries: LedgerEntry[],
    startDateStr: string,
    endDateStr: string,
    classification: string
) => {
    const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4'
    });

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;

    // Auto-generated reference
    const now = new Date();
    const dateStr = now.toISOString().split('T')[0].replace(/-/g, '');
    const timeStr = now.toTimeString().slice(0, 5).replace(':', '');
    const docRef = `SL-ORG-${dateStr}-${timeStr}`;

    // Filter entries by date explicitly
    const start = new Date(startDateStr);
    const end = new Date(endDateStr);
    end.setHours(23, 59, 59, 999); // Include full end date

    const filtered = entries.filter(e => {
        const d = new Date(e.created_at);
        return d >= start && d <= end;
    });

    // We track Y position globally
    let y = margin;

    // Helper: Add new page, resetting Y and re-drawing footer wrapper space
    const checkPageBreak = (requiredHeight: number) => {
        if (y + requiredHeight > pageHeight - margin - 15) { // 15mm for footer space
            doc.addPage();
            y = margin;
            return true;
        }
        return false;
    };

    // ------------- SECTION 1: Document Control Block -------------

    // Top Left: Branding
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...hexToRgb(COLORS.navy));
    doc.text("AlturaGov Governance Engine", margin, y);

    // Top Right: Classification
    if (classification) {
        doc.setFont("helvetica", "bold");
        doc.text(classification.toUpperCase(), pageWidth - margin, y, { align: 'right' });
    }

    y += 15;

    // Document Title (Weighted Serif fallback, as jsPDF standard font 'times' is serif)
    doc.setFont("times", "bold");
    doc.setFontSize(18);
    doc.text("STRATEGIC LEDGER & RECORD OF DECISIONS", pageWidth / 2, y, { align: 'center' });

    y += 12;

    // Metadata Table
    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(...hexToRgb(COLORS.primaryText));

    const metaKeys = ["Organisation", "Reporting Period", "Generated By", "Export Timestamp", "Document Reference"];
    const metaVals = [
        "Government Department", // Hardcoded for this mockup
        `${startDateStr} to ${endDateStr}`,
        "System Administrator",
        now.toLocaleString('en-NZ', { timeZoneName: 'short' }),
        docRef
    ];

    metaKeys.forEach((key, i) => {
        doc.setFont("helvetica", "bold");
        doc.text(key, margin, y);
        doc.setFont("helvetica", "normal");
        doc.text(metaVals[i], margin + 40, y);
        y += 6;
    });

    y += 10;

    // ------------- SECTION 2: Executive Summary -------------

    // Calculations
    const totalDecisions = filtered.length;
    const resequenced = filtered.filter(e => e.action_type === 'update' && e.rationale.includes('Re-sequenced')).length;
    const suspended = filtered.filter(e => e.action_type === 'pause').length;
    const tensionEvents = filtered.filter(e => {
        const m = e.initiatives?.approval_mandate;
        const p = e.initiatives?.relative_priority;
        return (m === 'Cabinet Approved' || m === 'Ministerial Approved') && (p === 'Tier 2' || p === 'Tier 3');
    }).length;
    const outOfSession = filtered.filter(e => e.committed_outside_meeting).length;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...hexToRgb(COLORS.navy));
    doc.text("Executive Summary of Activity", margin, y);
    y += 8;

    // Metrics grid (2x2)
    doc.setFontSize(10);
    const col1 = margin;
    const col2 = margin + 80;

    doc.setFont("helvetica", "bold");
    doc.setTextColor(...hexToRgb(COLORS.primaryText));
    doc.text("Total Decisions Recorded:", col1, y);
    doc.setFont("helvetica", "normal");
    doc.text(totalDecisions.toString(), col1 + 50, y);

    doc.setFont("helvetica", "bold");
    doc.text("Requirements Halted/Suspended:", col2, y);
    doc.setFont("helvetica", "normal");
    doc.text(suspended.toString(), col2 + 60, y);
    y += 6;

    doc.setFont("helvetica", "bold");
    doc.text("Initiatives Re-sequenced:", col1, y);
    doc.setFont("helvetica", "normal");
    doc.text(resequenced.toString(), col1 + 50, y);

    doc.setFont("helvetica", "bold");
    doc.text("Mandate Tension Events:", col2, y);
    doc.setFont("helvetica", "normal");
    doc.text(tensionEvents.toString(), col2 + 60, y);
    y += 10;

    if (outOfSession > 0) {
        doc.setFont("helvetica", "italic");
        doc.setFontSize(10);
        // Using strict framing from spec
        const osText = `${outOfSession} decision(s) in this period were committed outside a formal governance session. These entries are individually identified in the Decision Register below.`;
        const lines = doc.splitTextToSize(osText, pageWidth - (margin * 2));
        doc.text(lines, margin, y);
        y += (lines.length * 5) + 5;
    }

    y += 10;

    // ------------- SECTION 3: Open Mandate Tension Register -------------

    checkPageBreak(30);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...hexToRgb(COLORS.navy));
    doc.text("Open Mandate Tension Register", margin, y);
    y += 8;

    // The spec asks for ALL initiatives that CURRENTLY have mandate tension at time of export.
    // In our payload, we don't have the current state of *all* initiatives, we only have the historical ledger.
    // However, the spec states: "all initiatives that, at the time of export, carry an active Mandate Tension flag".
    // We will extract the *latest* state of any tensioned initiative from the historical log for this export period.
    const uniqueInitiatives = new Map();
    filtered.forEach(e => {
        if (!uniqueInitiatives.has(e.initiative_id)) {
            uniqueInitiatives.set(e.initiative_id, e);
        }
    });

    const activeTensions = Array.from(uniqueInitiatives.values()).filter(e => {
        const m = e.initiatives?.approval_mandate;
        const p = e.initiatives?.relative_priority;
        return (m === 'Cabinet Approved' || m === 'Ministerial Approved') && (p === 'Tier 2' || p === 'Tier 3');
    });

    if (activeTensions.length === 0) {
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(...hexToRgb(COLORS.primaryText));
        doc.text("No open mandate tensions recorded at time of export.", margin, y);
        y += 10;
    } else {
        // Table Headers
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.setTextColor(...hexToRgb(COLORS.primaryText));

        const c1 = margin;
        const c2 = margin + 50;
        const c3 = margin + 100;
        const c4 = margin + 140;

        doc.text("Initiative Name", c1, y);
        doc.text("Approval Mandate", c2, y);
        doc.text("Current Priority", c3, y);
        doc.text("Tension Recorded", c4, y);

        y += 4;
        doc.setDrawColor(...hexToRgb(COLORS.border));
        doc.line(margin, y, pageWidth - margin, y);
        y += 6;

        doc.setFont("helvetica", "normal");
        activeTensions.forEach(e => {
            const h = 6;
            if (checkPageBreak(h)) {
                // Redraw headers on new page
                doc.setFont("helvetica", "bold");
                doc.text("Initiative Name", c1, y);
                doc.text("Approval Mandate", c2, y);
                doc.text("Current Priority", c3, y);
                doc.text("Tension Recorded", c4, y);
                y += 4;
                doc.setDrawColor(...hexToRgb(COLORS.border));
                doc.line(margin, y, pageWidth - margin, y);
                y += 6;
                doc.setFont("helvetica", "normal");
            }

            const titleStr = doc.splitTextToSize(e.initiatives?.title || 'Unknown', 45);
            doc.text(titleStr, c1, y);
            doc.text(e.initiatives?.approval_mandate || '', c2, y);
            doc.text(e.initiatives?.relative_priority || '', c3, y);
            doc.text(new Date(e.created_at).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }), c4, y);

            y += (titleStr.length * 4) + 2;
        });

        y += 4;
        doc.setFont("helvetica", "italic");
        doc.setFontSize(9);
        const tensionContext = "Mandate tensions represent initiatives carrying formal political or governance sanction that are currently classified below Tier 1 delivery priority. Each item in this register requires a documented governance decision.";
        const lines = doc.splitTextToSize(tensionContext, pageWidth - (margin * 2));
        doc.text(lines, margin, y);
        y += (lines.length * 4) + 10;
    }

    // ------------- SECTION 4: Decision Register -------------

    checkPageBreak(20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...hexToRgb(COLORS.navy));
    doc.text("Decision Register", margin, y);
    y += 10;

    // Grouping by Date and Session Type
    // Sorting oldest first (chronologically ascending per spec)
    const ascFiltered = [...filtered].sort((a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime());

    // We will group by a composite key: "Date|isOutsideSession"
    const groups = new Map<string, LedgerEntry[]>();

    ascFiltered.forEach(e => {
        const d = new Date(e.created_at);
        const dateKey = d.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' });
        const typeKey = e.committed_outside_meeting ? "OUT" : "SESSION";
        const key = `${dateKey}|${typeKey}`;

        if (!groups.has(key)) groups.set(key, []);
        groups.get(key)!.push(e);
    });

    // To ensure "Session entries first" on the same date, we sort the keys
    const sortedKeys = Array.from(groups.keys()).sort((a, b) => {
        const [dateA, typeA] = a.split('|');
        const [dateB, typeB] = b.split('|');

        // Parse dates for sorting
        const timeA = new Date(dateA).getTime();
        const timeB = new Date(dateB).getTime();

        if (timeA !== timeB) return timeA - timeB;
        if (typeA !== typeB) return typeA === 'SESSION' ? -1 : 1;
        return 0;
    });

    sortedKeys.forEach(key => {
        const [dateStr, type] = key.split('|');
        const groupEntries = groups.get(key)!;

        // Group Header
        checkPageBreak(15);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(...hexToRgb(COLORS.navy));

        if (type === 'SESSION') {
            doc.text(`Formal Governance Session — ${dateStr}`, margin, y);
        } else {
            doc.text(`Out-of-Session Commitments — ${dateStr}`, margin, y);
        }
        y += 8;

        // Render Entries
        groupEntries.forEach(entry => {
            const entryDate = new Date(entry.created_at);
            const timeStr = entryDate.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });

            // Calculate block height PRE-RENDER to avoid splitting
            // 1. Timestamp line (5mm)
            // 2. Badges (8mm)
            // 3. Action Title (8mm)
            // 4. Rationale (varies)

            doc.setFont("helvetica", "italic");
            doc.setFontSize(9);
            const rationaleText = entry.rationale ? entry.rationale : "No rationale recorded at time of commitment.";
            const rationaleLines = doc.splitTextToSize(rationaleText, pageWidth - (margin * 2) - 10);

            // Estimated height
            const estHeight = 5 + 8 + 8 + (rationaleLines.length * 5) + 8;

            checkPageBreak(estHeight);

            // Divider Line
            doc.setDrawColor(...hexToRgb(COLORS.border));
            doc.setLineWidth(0.5);
            doc.line(margin, y, pageWidth - margin, y);
            y += 5;

            // Timestamp + Actor
            doc.setFont("helvetica", "bold");
            doc.setFontSize(9);
            doc.setTextColor(...hexToRgb(COLORS.primaryText));
            doc.text(`${dateStr}  ${timeStr}`, margin, y);

            doc.setFont("helvetica", "normal");
            const actor = `Acted by: ${entry.users?.email?.split('@')[0] || 'Unknown'}`;
            doc.text(actor, margin + 40, y);
            y += 6;

            // Badges
            const isOut = entry.committed_outside_meeting;
            const badgeBg = isOut ? COLORS.badgeOutBg : COLORS.badgeFormalBg;
            const badgeTextCol = isOut ? COLORS.badgeOutText : COLORS.badgeFormalText;
            const badgeText = isOut ? "OUT-OF-SESSION COMMITMENT" : "FORMAL GOVERNANCE SESSION";

            doc.setFont("helvetica", "bold");
            doc.setFontSize(8);
            const badgeWidth = doc.getTextWidth(badgeText) + 6;

            doc.setFillColor(...hexToRgb(badgeBg));
            doc.rect(margin, y, badgeWidth, 6, "F");

            if (isOut) {
                // Heavier border for warning badge
                doc.setDrawColor(...hexToRgb(badgeTextCol));
                doc.setLineWidth(0.5);
                doc.rect(margin, y, badgeWidth, 6, "S");
            }

            doc.setTextColor(...hexToRgb(badgeTextCol));
            doc.text(badgeText, margin + 3, y + 4.2);

            let offsetX = margin + badgeWidth + 5;

            // Mandate Flag
            const m = entry.initiatives?.approval_mandate;
            if (m === 'Cabinet Approved' || m === 'Ministerial Approved') {
                const flagText = `⚠ ${m === 'Cabinet Approved' ? 'CABINET' : 'MINISTERIAL'} MANDATE AFFECTED`;
                doc.setTextColor(...hexToRgb(COLORS.warning));
                doc.text(flagText, offsetX, y + 4.2);
            }

            y += 10;

            // The Action
            doc.setFont("helvetica", "bold");
            doc.setFontSize(10);
            doc.setTextColor(...hexToRgb(COLORS.navy));
            const actionCap = entry.action_type === 'update' ? 'UPDATED' : entry.action_type.toUpperCase();
            doc.text(`${actionCap} — ${entry.initiatives?.title || 'Unknown Initiative'}`, margin, y);
            y += 6;

            // The Rationale
            doc.setFont("helvetica", "italic");
            doc.setFontSize(9);
            doc.setTextColor(...hexToRgb(COLORS.primaryText));

            // Draw left border
            doc.setDrawColor(...hexToRgb(COLORS.rationaleBorder));
            doc.setLineWidth(0.8);
            doc.line(margin + 5, y + 1, margin + 5, y + (rationaleLines.length * 4.5));

            doc.text(rationaleLines, margin + 10, y + 3);
            y += (rationaleLines.length * 4.5) + 8;
        });
    });

    // ------------- SECTION 5 & 6 -------------

    checkPageBreak(50);
    y += 10;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...hexToRgb(COLORS.navy));
    doc.text("Data Integrity Statement", margin, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...hexToRgb(COLORS.primaryText));
    const integrityText = "Entries in the AlturaGov Strategic Ledger are written as append-only records. No entry can be modified or deleted after creation. Row-level security policies enforce this constraint at the database layer. This document represents a complete and unaltered extract of all ledger entries for the specified reporting period. The export timestamp and generating user identity are system-verified at the moment of generation.";
    const integrityLines = doc.splitTextToSize(integrityText, pageWidth - (margin * 2));
    doc.text(integrityLines, margin, y);
    y += (integrityLines.length * 5) + 15;

    // Signatures
    doc.setFont("helvetica", "italic");
    const signContext = "This document has been generated from the AlturaGov Strategic Ledger and represents the complete record of governance decisions for the period specified above.";
    const signLines = doc.splitTextToSize(signContext, pageWidth - (margin * 2));
    doc.text(signLines, margin, y);
    y += 20;

    doc.setFont("helvetica", "normal");
    doc.text("Verified by (PMO):", margin, y);
    doc.line(margin + 40, y + 1, margin + 120, y + 1);
    y += 15;

    doc.text("Approved by (Executive):", margin, y);
    doc.line(margin + 40, y + 1, margin + 120, y + 1);
    y += 10;

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Document Reference: ${docRef}. Generated: ${now.toLocaleString('en-NZ')}.`, margin, y);

    // ------------- PAGE FOOTERS -------------
    const totalPages = doc.getNumberOfPages();

    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);

        const footerY = pageHeight - 12;

        // Left
        doc.text(`AlturaGov Strategic Ledger — Government Department — ${startDateStr} to ${endDateStr}`, margin, footerY);

        // Center
        doc.text(docRef, pageWidth / 2, footerY, { align: 'center' });

        // Right
        let rightText = `Page ${i} of ${totalPages}`;
        if (classification) {
            rightText = `${classification.toUpperCase()}  |  ${rightText}`;
        }

        doc.text(rightText, pageWidth - margin, footerY, { align: 'right' });
    }

    doc.save(`SL_${docRef}.pdf`);
};
